### ISSUE TITLE
Find Diff Async

### ISSUE THREAD

**Issue by JacekLangerTUDA** [JackLanger/Bahnkurve#6]
Die Methode zum finden der Steigerungs rate muss asynchron so ausgeführt werden, dass sie Den Mainthread nicht blockiert aber fertig ist bevor weitere werte erzeugt werden.

[bahnkurve] Achterbahn/algo/Bahnkurve.cs (Lines 76-100)

```

private double FindDiff(double startAngle)
    {
        var beta = 0.0;
        var alpha = startAngle;
        var y = calcY(0, alpha);
        while (beta < 180)
        {
            beta += alpha;
            y = calcY(y, beta);
            var f = CalcForce(y, alpha, beta - alpha);

            if (f > 4.5 || f < 0)
            {
                Diff = f < 0 ? Diff * 1.05 : Diff -= 0.05;
                if (Diff < 0.05) startAngle *= 0.9;
                beta = 0;
                alpha = startAngle;
                y = calcY(0, alpha);
            }

            alpha += Diff;
        }

        return startAngle;
    }
```

[Open in IDE](https://api.codestream.com/c/YxYAqWiBmj0Oj0i-/tzwCN2yOTWKRRCntbRfUEg?marker=631742416bd5f1bc9b28d3c9&ide=default&src=GitHub) · [Open on GitHub](https://github.com/jacklanger/bahnkurve/blob/249e55d0cc50e63b50c98ac5e2559a99ac71993b/Achterbahn/algo/Bahnkurve.cs#L76-L100)

<sup>Created from JetBrains using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=issue&utm_campaign=github)</sup>

**Comment by JackLanger** [comment]
Wird Von GUI als Async Task aufgerufen.
